version: '2'
services:
  control:
    container_name: chaos-control
    hostname: control
    build: ./control
    env_file: ./secret/control.env
    privileged: true
    links:
      - n1
      - n2
      - n3
      - n4
      - n5
  node:
    container_name: chaos-node
    build: ./node
    env_file: ./secret/node.env
    privileged: true
  n1:
    extends: node
    container_name: chaos-n1
    hostname: n1
  n2:
    extends: node
    container_name: chaos-n2
    hostname: n2
  n3:
    extends: node
    container_name: chaos-n3
    hostname: n3
  n4:
    extends: node
    container_name: chaos-n4
    hostname: n4
  n5:
    extends: node
    container_name: chaos-n5
    hostname: n5
